#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/onedr0p/bazarr
  tag:
  pullPolicy: IfNotPresent

env:
  - name: TZ
    value: UTC
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  main:
    ports:
      http:
        port: 6767


persistence:
  configs:
    type: pvc
    mountPath: "/config"
    subPath:  "/bazarr" 
    existingClaim: media-ssd 

  library:
    type: pvc
    mountPath: "/movies"
    subPath: "/movies" 
    existingClaim: media-ssd 

  media:
    enabled: false
    mountPath: /media
