apiVersion: v1
kind: PersistentVolume
metadata:
  name: "grafana-ssd"
  labels:
    type: "local"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/grafana"
