service:
  ui:
    type: ClusterIP
    nodePort: null
  manager:
    type: ClusterIP
    nodePort: ""

defaultSettings:
  defaultDataPath: /mnt/ssd

ingress:
  enabled: true
  host: longhorn.192.168.0.20.nip.io
