apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "isak-friis-jespersen.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "isak-friis-jespersen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "isak-friis-jespersen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "isak-friis-jespersen.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
