apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | default "traefik" | quote }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | default (printf "media.%s.nip.io" .Values.ingress.ip) }}
      http:
        paths:
          {{- if .Values.transmission.enabled }}
          - path: "/transmission"
            pathType: Prefix
            backend:
              service:
                name: "transmission-transmission-openvpn"
                port:
                  number: 80
          {{- end }}
          {{- if .Values.sonarr.enabled }}
          - path: "/sonarr"
            pathType: Prefix
            backend:
              service:
                name: "sonarr"
                port:
                  number: 80
          {{- end }}
          {{- if .Values.radarr.enabled }}
          - path: "/radarr"
            pathType: Prefix
            backend:
              service:
                name: "radarr"
                port:
                  number: 80
          {{- end }}
          {{- if .Values.prowlarr.enabled }}
          - path: "/prowlarr"
            pathType: Prefix
            backend:
              service:
                name: "prowlarr"
                port:
                  number: 80
          {{- end }}
          {{- if .Values.emby.enabled }}
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "emby"
                port:
                  number: 8096
          {{- end }}
