replicaCount: 1

image:
  repository: linuxserver/emby
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: UID
    value: "1000"
  - name: GID
    value: "1000"

service:
  type: LoadBalancer
  port: 8096

volumes:
  - name: "media-ssd"
    persistentVolumeClaim:
      claimName: "media-ssd" # PersistentVolumeClaim created earlier

volumeMounts:
  - name: "media-ssd"
    mountPath: "/config"
    subPath: "configs/emby"
  - name: "media-ssd"
    mountPath: "/movies"
    subPath: "library/movies"
  - name: "media-ssd"
    mountPath: "/tv"
    subPath: "library/tv"

