apiVersion: v1
kind: PersistentVolume
metadata:
  name: "monitoring-ssd"
  labels:
    type: "local"
spec:
  capacity:
    storage: "50Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/influxdb"
