image:
  repository: influxdb
  tag: 2.7.4-alpine
  pullPolicy: IfNotPresent


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi


livenessProbe:
  path: "/health"
  scheme: "HTTP"
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3

readinessProbe:
  path: "/health"
  scheme: "HTTP"
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

startupProbe:
  enabled: true
  path: "/health"
  scheme: "HTTP"
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 6

adminUser:
  organization: "influxdata"
  bucket: "default"
  user: "admin"
  retention_policy: "0s"
  ## Leave empty to generate a random password and token.
  ## Or fill any of these values to use fixed values.
  password: ""
  token: ""

persistence:
  enabled: true
  useExisting: true
  name: "monitoring-ssd"
  accessMode: ReadWriteOnce
  size: 50Gi
  mountPath: /var/lib/influxdb2
  subPath: ""


service:
  type: LoadBalancer 
  port: 8086 
  targetPort: 8086
  annotations: {}
  labels: {}
  portName: http

serviceAccount:
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  # Annotations for the ServiceAccount
  annotations: {}


pdb:
  ## Specifies whether a Pod disruption budget should be created
  create: true
  minAvailable: 1
  # maxUnavailable: 1
